# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/deadpool/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),deadpool)

$(call add-radio-file-sha1-checked,radio/bootloader.img,3cdc3a2bf65c9d88b169055a7fd436b5145d1128)

endif
